apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats
  template:
    metadata:
      labels:
        app: nats
    spec:
      containers:
        - name: nats
          image: nats-streaming:0.17.0
          args: [
              '-p', # port
              '4222', # -p
              '-m', # monitoring port
              '8222', # -m
              '-hbi', # Heart beat interval. How often hb is sent.
              '5s', # -hbi
              '-hbt', # How long each client has to respond
              '5s', # -hbt
              '-hbf', # How often each client can fail before NATS assumes it's dead
              '2', # -hbf
              '-SD', # Enable STAN debugging output
              '-cid', # Cluster id
              'ticketing', # -cid
            ] # commandline options used when creating the container
---
apiVersion: v1
kind: Service
metadata:
  name: nats-srv
spec:
  selector:
    app: nats
  ports:
    - name: client
      protocol: TCP
      port: 4222
      targetPort: 4222
    - name: monitoring
      protocol: TCP
      port: 8222
      targetPort: 8222
