name: deploy-auth

on:
  push:
    branches:
      - master
    paths:
      - 'ticketing/auth/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd auth && docker build -t pallimoon/auth .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env: # Secrets that have been set on the Github repo
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push pallimoon/auth
