name: deploy-client

on:
  push:
    branches:
      - master
    paths:
      - 'ticketing/client/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd ticketing/client && docker build -t pallimoon/client .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env: # Secrets that have been set on the Github repo
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push pallimoon/client
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save ticketing
      - run: kubectl rollout restart deployment client-depl
